### ISSUE TITLE
Missing E739 Checkbox glyph

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno.fonts#13]
## Current behavior

Code here:
```C#
        public readonly FontIcon CheckboxIcon = new FontIcon() { FontFamily = (FontFamily)Application.Current.Resources["SymbolThemeFontFamily"], Glyph = "\uE739" };
        AutoJoin.Icon = CheckboxIcon;
```

E739 shows nothing:
![image](https://user-images.githubusercontent.com/57174311/114040616-fd37f880-98ad-11eb-9b68-ffcb48634dc2.png)

## Expected behavior
Shows an empty Checkbox like in UWP's font Segoe MDL2:
![image](https://user-images.githubusercontent.com/57174311/114041021-5a33ae80-98ae-11eb-9383-2c0b3c171e6c.png)

## How to reproduce it (as minimally and precisely as possible)

1. Create a Uno Platform Project
2. Create a `NavigationViewItem` in XAML, name it AutoJoin.
3. Compile the project for UWP and for WASM, then compare the results.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.9.3)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
I think this is already fixed.

**Comment by d2dyno1** [comment]
I can confirm it's fixed
![image](https://github.com/user-attachments/assets/dba072c4-3019-4bae-9bfe-fedba93cf48f)
