### ISSUE TITLE
NuGet package shouldn't have a public class `Class1`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.fonts#24]
Looking into the dll in the NuGet package, it has a public class `Class1` (the only API in the package).

Ideally, we shouldn't have to have a dll at all. @jeromelaban I expect this was done to workaround some error, what was the error?

At the very least, the dll shouldn't have any public APIs.

**Comment by jeromelaban** [comment]
It's not exactly a workaround, but it's more related to the way uno deals with content files and how the lookup for transitive assets work in Uno. It's done through lookup from runtime items, and those are not included automatically using the default nuget behavior. 

Still, having class1 is not particularly useful, I agree :) I'll remove it. Thanks!

**Comment by Youssef1313** [comment]
@jeromelaban I'm taking a lot.

**Comment by Youssef1313** [comment]
Oh I see you did that in https://github.com/unoplatform/uno.fonts/pull/25.

Though I worked on an approach to avoid having the dll completely, and also moved to csproj instead of nuspec (that's more modern and manageable approach).

**Comment by Youssef1313** [comment]
Closing as fixed by #25
