### ISSUE TITLE
Missing glyphs in Fluent icons

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.fonts#47]
## Current behavior

Missing the following:

- E708 - Quiet hours
- E62E - Pause solid (seems the same as F8AE)
- F2B7 - LocaleLanguage
- F71C - StartPresenting
- F540 - Safe
- EC19 - PLAP (This one shows the wrong icon, it should be PLAP)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by d2dyno1** [comment]
I found more missing icons that I used in my project:
- F2B7 - LocaleLanguage
- F71C - StartPresenting
- F540 - Safe
- EC19 - PLAP (**This one shows the wrong icon, it should be PLAP**)

@MartinZikmund

**Comment by agneszitte** [comment]
@MartinZikmund normally same comment as https://github.com/unoplatform/uno/issues/18148#issuecomment-2364460908

**Comment by MartinZikmund** [comment]
It seems `<FontIcon Glyph="&#xF2B7;" />` is not working, need to verify, reopening for now to track

**Comment by agneszitte** [comment]
@MartinZikmund I will let you verify quickly a last time on your side all the icons for https://github.com/unoplatform/uno/issues/18148 and https://github.com/unoplatform/uno.fonts/issues/47. This is to ensure that no icons are missing based on the latest changes. 
Once everything is properly addressed, feel free to close both issues, and we can proceed with a fresh round of QA.

**Comment by MartinZikmund** [comment]
The only missing from this list is E62E, which has F8AE as an alternative, so it is not urgent. Closing this, and opening a new issue to track new batch of icons to be added at a later point.

**Comment by MartinZikmund** [comment]
The glyphs in our font, although very similar, are not exact copy of the Segoe Fluent Icons font, which unfortunately does not have an open license...

**Comment by agneszitte** [comment]
> The only missing from this list is E62E, which has F8AE as an alternative, so it is not urgent. Closing this, and opening a new issue to track new batch of icons to be added at a later point.

@MartinZikmund can you share the link for the new issue for reference please
