### ISSUE TITLE
Remove duplicate icons

### ISSUE THREAD

**Issue by StefanJanssen95** [unoplatform/uno.fonts#7]
## What would you like to be added:
I would like to get rid of duplicate icons. 

## Why is this needed:
Quite a few icons are repeated multiple times while they are the exact same, others are really similar but are no direct copies. Removing a few of the duplicates can decrease the font size.

## Anything else we need to know?
I've assembled the following list by matching on the glyph names. These icons have the exact same name while there might be ones with a minor difference in the name as well.
![image](https://user-images.githubusercontent.com/6250246/95108866-1e236380-073c-11eb-96bd-3225af6b278b.png)

**Comment by davidjohnoliver** [comment]
Thanks for the report!

Per the readme:

>Uno FluentUI Assets is intended to be a drop-in replacement for Microsoft's Segoe MDL2 Assets font

'Drop-in replacement' means that for every glyph in the [Segoe MDL2 Assets font](https://docs.microsoft.com/en-us/typography/font-list/segoe-mdl2-assets), there should be an equivalent icon at the same glyph position in the Uno FluentUI Assets font. This is to support using existing [UWP codebases](https://docs.microsoft.com/en-us/windows/uwp/get-started/) (that may [refer directly to the glyph code](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.fonticon)) with the cross-platform [Uno Platform framework](https://platform.uno/).

So, wherever there's duplication in Segoe MDL2, there'll necessarily be duplication in Uno FluentUI Assets as well. And there is, for whatever reason, a great deal of duplication in Segoe. I think there's at least 5 occurrences of a checkmark, for example.

I'm going to close this issue for now; feel free to open a new one if you notice specific instances where there's duplication in Uno's font that's not matched by Segoe.
