### ISSUE TITLE
E76B does not match UWP

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.fonts#9]
## Current behavior

The symbol E76B is not an inverse of E76C:

![image](https://user-images.githubusercontent.com/1075116/99814834-d325aa00-2b49-11eb-9dfc-b8e4e4ba25f6.png)

## Expected behavior

E76B should be an inverse of E76C

**Comment by robloo** [comment]
Was going to file a report but decided to check first here :)

This issue is present in a custom app. But it's also a problem in the pager control: 
![](https://uno-website-assets.s3.amazonaws.com/wp-content/uploads/2021/02/11105604/pagercontrol1.gif)

**Comment by MartinZikmund** [comment]
@robloo seems the font files were not updated properly in solution template/WASM CSS

**Comment by robloo** [comment]
Is this going to be fixed in upcoming releases?

**Comment by Youssef1313** [comment]
I think this is already fixed. @MartinZikmund Can you double check?

**Comment by MartinZikmund** [comment]
Indeed it is!
